version: '3.7'

services:
  facile-budget:
    container_name: facile-budget
    build: .
    restart: always
    volumes:
      - storage/FacileBudget:/app
    networks:
      - lan-network
    ports:
      - 5004:5004

networks:
  lan-network:
    external:
      name: docker-lan